<?php

namespace Tests\Unit;

use CodeIgniter\Test\CIUnitTestCase;
use App\Models\AgentModel;

/**
 * Test the Agent ID Generation functionality
 *
 * This test verifies that:
 * 1. Sequential ID generation produces WRR00001, WRR00002, etc.
 * 2. Agent creation process works end-to-end
 * 3. Database operations complete successfully
 */
class AgentIdGenerationTest extends CIUnitTestCase
{
    protected $agentModel;

    protected function setUp(): void
    {
        parent::setUp();
        $this->agentModel = new AgentModel();
    }

    /**
     * Test that unique ID generation produces correct format
     */
    public function testUniqueIdGenerationFormat()
    {
        $uniqueId = $this->agentModel->generateUniqueId();

        // Assert that the ID follows the expected pattern
        $this->assertMatchesRegularExpression('/^WRR\d{5}$/', $uniqueId);

        // Assert that it starts with WRR
        $this->assertStringStartsWith('WRR', $uniqueId);

        // Assert that the numeric part is exactly 5 digits
        $numericPart = substr($uniqueId, 3);
        $this->assertIsNumeric($numericPart);
        $this->assertEquals(5, strlen($numericPart));
    }

    /**
     * Test that sequential ID generation works correctly
     */
    public function testSequentialIdGeneration()
    {
        // Generate multiple IDs to test sequential nature
        $id1 = $this->agentModel->generateUniqueId();
        $id2 = $this->agentModel->generateUniqueId();

        // Extract numeric parts
        $num1 = (int) substr($id1, 3);
        $num2 = (int) substr($id2, 3);

        // The second ID should be greater than the first
        $this->assertGreaterThan($num1, $num2);
    }

    /**
     * Test that agent creation with auto-generated ID works
     */
    public function testAgentCreationWithAutoGeneratedId()
    {
        $testData = [
            'name' => 'Test Agent ID Generation',
            'email' => 'test_id_gen_' . time() . '@example.com',
            'phone' => '+91 7000000000',
            'address' => 'Test Address for ID Generation',
            'qualification' => 'Test Qualification',
            'password' => 'testpass123',
            'is_active' => true
        ];

        // Create agent
        $this->agentModel->skipValidation(true);
        $agentId = $this->agentModel->insert($testData);

        $this->assertIsInt($agentId);

        // Retrieve the created agent
        $createdAgent = $this->agentModel->find($agentId);
        $this->assertNotNull($createdAgent);

        // Verify that unique_agent_id was generated
        $this->assertNotNull($createdAgent['unique_agent_id']);
        $this->assertMatchesRegularExpression('/^WRR\d{5}$/', $createdAgent['unique_agent_id']);

        // Clean up
        $this->agentModel->delete($agentId);
    }

    /**
     * Test that error handling provides user-friendly messages
     */
    public function testErrorHandlingForInvalidData()
    {
        $invalidData = [
            'name' => '', // Required field empty
            'email' => 'invalid-email', // Invalid email format
            'phone' => '+91 7000000000',
        ];

        $this->agentModel->skipValidation(false);
        $agentId = $this->agentModel->insert($invalidData);

        // Should return false for invalid data
        $this->assertFalse($agentId);

        // Should have validation errors
        $errors = $this->agentModel->errors();
        $this->assertNotEmpty($errors);
    }

    /**
     * Test that database operations complete successfully
     */
    public function testDatabaseOperations()
    {
        // Test basic database connectivity
        $agents = $this->agentModel->findAll();
        $this->assertIsArray($agents);

        // Test count operation
        $count = $this->agentModel->countAllResults();
        $this->assertIsInt($count);
        $this->assertGreaterThanOrEqual(0, $count);

        // Test statistics
        $stats = $this->agentModel->getStatistics();
        $this->assertIsArray($stats);
        $this->assertArrayHasKey('total', $stats);
        $this->assertArrayHasKey('active', $stats);
        $this->assertArrayHasKey('inactive', $stats);
    }
}